version: '2'

services:

  mongo:
    image: mongo:latest
    container_name: mongo
    hostname: mongo
    ports:
      - "27017:27017"
    volumes:
      - "${MONGO_DATA}:/data/db"

  mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql
    hostname: mysql
    stdin_open: true
    tty: true
    ports:
      - "3306:3306"
    environment:
       #MYSQL_USER: user
       #MYSQL_PASSWORD: passwd
       MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
       MYSQL_CLIENT: '%.%.%.%'
    volumes:
      - ./conf/mysql:/etc/mysql/conf.d
      - "${MYSQL_DATA}:/var/lib/mysql"

  php-fpm:
    build:
      context: .
      dockerfile: Dockerfile.php${PHP_VERSION}-fpm.alpine
    container_name: php-fpm
    ports:
      - "9000:9000"
    volumes:
      - "${WWW_DATA}:/var/www/html"
    links:
      - mysql
    depends_on:
      - mysql

  web:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "${WWW_DATA}:/var/www/html"
      - "${NGINX_HOSTS_CONF}:/etc/nginx/conf.d"
      - ./conf/nginx/nginx.conf:/etc/nginx/nginx.conf
    links:
      - php-fpm
      - mysql
    depends_on:
      - php-fpm
